### ISSUE TITLE
My data is width 1438, height 1090, depth 100

### ISSUE THREAD

**Issue by kt7456** [Twinklebear/webgl-volume-raycaster#21]
May I ask how to modify it so that it can be displayed correctly

**Comment by Twinklebear** [comment]
What issue are you seeing? It's not scaled properly? You should be able to make a 3d texture with those dimensions, upload your data, and view it. If the scaling isn't right, try changing `volScale`:  https://github.com/Twinklebear/webgl-volume-raycaster/blob/master/js/volume-raycaster.js#L120-L121 to rescale it properly.

**Comment by kt7456** [comment]
> 它没有正确缩


This data cannot be rendered correctly: 
[test_1438x1090x13_uint8.zip](https://github.com/Twinklebear/webgl-volume-raycaster/files/11713613/test_1438x1090x13_uint8.zip)

This data renders correctly： 
[test_1440x1440x14_uint8.zip](https://github.com/Twinklebear/webgl-volume-raycaster/files/11713612/test_1440x1440x14_uint8.zip)
1438x1090*13 file can use paraview software to render correctly：
![image](https://github.com/Twinklebear/webgl-volume-raycaster/assets/35618730/55efea0b-3ed2-495f-b5d7-b6f640505f04)

1438x1090x13 file can't render correctly with code:
![image](https://github.com/Twinklebear/webgl-volume-raycaster/assets/35618730/9e2d2ccf-afa6-4e61-993f-9925659795c3)
1440x1440x14 file can be rendered correctly with code：
![image](https://github.com/Twinklebear/webgl-volume-raycaster/assets/35618730/a5b22114-583d-4955-b468-c87bf1129fe9)

first picture viewed with paraview software. second picture and third  picture rendered with code. It feels that it is not as simple as modifying volscale. If the aspect ratio is not 1:1, there is no way to render it correctly, but my data width and height are not 1:1.
As you can see, the second picture is distorted, and the first and third picture they are normal

**Comment by Twinklebear** [comment]
Yeah, the middle picture also looks like it may have some striding or alignment issue going on when you created the volume data, because it seems to have this shift along the rows of the image. I'd double check how you're creating the volume, maybe there is some padding or alignment rule that needs to be followed that you're not here, or you have some incorrect offset/stride/size in the volume upload code.

**Comment by kt7456** [comment]
> Yeah, the middle picture also looks like it may have some striding or alignment issue going on when you created the volume data, because it seems to have this shift along the rows of the image. I'd double check how you're creating the volume, maybe there is some padding or alignment rule that needs to be followed that you're not here, or you have some incorrect offset/stride/size in the volume upload code.

Thank you so much

**Comment by Twinklebear** [comment]
Something that just came to mind, in this repo I don't set the pixel store unpack alignment, so the default is 4. That might be what's causing the shift, since `1438 % 4 =  2`. So you could try setting the pixel unpack alignment to 1 (https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/pixelStorei)

```js
gl.pixelStorei(gl.UNPACK_ALIGNMENT, 1);
```

**Comment by kt7456** [comment]
> 

Thank you very much, the problem has been solved
