### ISSUE TITLE
How to get the value of mouseover

### ISSUE THREAD

**Issue by kt7456** [Twinklebear/webgl-volume-raycaster#22]
is a bit difficult for me, so I have to ask you，thanks！

**Comment by Twinklebear** [comment]
Can you clarify what you mean here? Like you want to know the value of the volume at the pixel under the cursor?

**Comment by kt7456** [comment]
> Can you clarify what you mean here? Like you want to know the value of the volume at the pixel under the cursor?

Yes，like this 
![1729832752368](https://github.com/user-attachments/assets/7211cd48-e76d-4ae0-8c7f-5e240a12a1c5)
This is my volume data file 
[temperature_512x512x101_unit8.zip](https://github.com/user-attachments/files/17516360/temperature_512x512x101_unit8.zip)

**Comment by Twinklebear** [comment]
So for a volume it's an ambiguous request, because the volume is drawn transparently and the final color at the pixel comes from blending together multiple samples along the ray through that pixel. So there really is no "single value" under the cursor.

Given that ambiguity, for a volume the best option is probably to pick the value of the most opaque sample along the ray as the "value for that pixel". Alternatively, if you're drawing surfaces as well (like a slice or isosurface), you can use the value of the slice/isosurface.

Once you've decided what the "value for a pixel" is, you can get it by just:
- Add an additional float32 render target to your renderer
- Output the value for the pixel to this render target
- When someone clicks the screen and you want to get the value, read the pixel value from this float32 render target

**Comment by kt7456** [comment]
> So for a volume it's an ambiguous request, because the volume is drawn transparently and the final color at the pixel comes from blending together multiple samples along the ray through that pixel. So there really is no "single value" under the cursor.
> 
> Given that ambiguity, for a volume the best option is probably to pick the value of the most opaque sample along the ray as the "value for that pixel". Alternatively, if you're drawing surfaces as well (like a slice or isosurface), you can use the value of the slice/isosurface.
> 
> Once you've decided what the "value for a pixel" is, you can get it by just:
> 
> * Add an additional float32 render target to your renderer
> * Output the value for the pixel to this render target
> * When someone clicks the screen and you want to get the value, read the pixel value from this float32 render target

thnaks! i'm done
